### ISSUE TITLE
Organization Cannot Load Users

### ISSUE THREAD

**Issue by AdmirilRed** [AdmirilRed/RedLibrary#5]
Full stack trace here. Has to do with user instantiation most likely.

> Exception in thread "main" org.hibernate.exception.GenericJDBCException: could not execute statement
> 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
> 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
> 	at org.hibernate.persister.collection.AbstractCollectionPersister.recreate(AbstractCollectionPersister.java:1313)
> 	at org.hibernate.action.internal.CollectionRecreateAction.execute(CollectionRecreateAction.java:50)
> 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:447)
> 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:333)
> 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:335)
> 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
> 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1224)
> 	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:464)
> 	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2894)
> 	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2270)
> 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:485)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:146)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:230)
> 	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
> 	at redlibrarian.UserInterface.load(UserInterface.java:69)
> 	at redlibrarian.RedLibrarian.main(RedLibrarian.java:24)
> Caused by: java.sql.SQLException: Field 'users_username' doesn't have a default value
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
> 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
> 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
> 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
> 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
> 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
> 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
> 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
> 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
> 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
> 	... 18 more

**Comment by AdmirilRed** [comment]
OrgUser has been deprecated.
